# Guided Project: Mobile App for Lottery Addiction

## Introduction

This project is about helping lottery addicts better estimate their chances of winning. A medical institute that aims to prevent and treat gambling addictions wants to build a dedicated mobile app. The institute has a team of engineers that will build the app, but they need to create the logical core of the app and calculate probabilities.
For the first version of the app, they want to focus on the 6/49 lottery. My goal is to build functions that enable users to answer questions like:
- What is the probability of winning the big prize with a single ticket?
- What is the probability of winning the big prize if we play 40 different tickets (or any other number)?
- What is the probability of having five (or four, or three, or two) winning numbers on a single ticket?

The institute also wants to consider historical data coming from the national 6/49 lottery game in Canada. The data set has data for 3,665 drawings, dating from 1982 to 2018.

## Core Functions

Lets write a function named factorial() which takes as input a number n and computes the factorial of that number n:

In [1]:
def factorial(n):
    final_product = 1
    for i in range(n, 0, -1):
        final_product *= i
    return final_product  


Lets write a function named combinations() which takes in two inputs (n and k) and outputs the number of combinations when I'm taking only k objects from a group of n objects.


In [2]:
def combinations(n, k):
     return factorial(n) / (factorial(k) * (factorial(n-k)))


## One-ticket Probability

In the 6/49 lottery, six numbers are drawn from a set of 49 numbers that range from 1 to 49. A player wins the big prize if the six numbers on their tickets match all the six numbers drawn. If a player has a ticket with the numbers {13, 22, 24, 27, 42, 44}, he only wins the big prize if the numbers drawn are {13, 22, 24, 27, 42, 44}. If only one number differs, he doesn't win.

For the first version of the app, I want players to be able to calculate the probability of winning the big prize with the various numbers they play on a single ticket (for each ticket a player chooses six numbers out of 49). 

Lets write a function named one_ticket_probability(), which takes in a list of six unique numbers and prints the probability of winning in a way that's easy to understand.


In [3]:
def one_ticket_probability(user_numbers):
    total_pos_outcomes = combinations(49, 6) 
    probability_1_ticket = 1 / total_pos_outcomes * 100
    return print('The probability of winning the big prize of your numbers {} is {:.6f}%. Other words, your chances is 1 in {:,}.'.format(user_numbers, probability_1_ticket,int(total_pos_outcomes)))


In [4]:
#Test one_ticket_probability(numbers) function:

user_list1 = [4, 13, 14, 9, 8, 45]
one_ticket_probability(user_list1)


The probability of winning the big prize of your numbers [4, 13, 14, 9, 8, 45] is 0.000007%. Other words, your chances is 1 in 13,983,816.


## Historical Data Check for Canada Lottery

Next I'll focus on exploring the historical data coming from the Canada 6/49 lottery. The data set can be downloaded from Kaggle and it has the following structure:

In [5]:
import pandas as pd

lottery  = pd.read_csv('649.csv')
lottery.head(3)

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
0      649            1                0  6/12/1982               3   
1      649            2                0  6/19/1982               8   
2      649            3                0  6/26/1982               1   

   NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
0              11              12              14              41   
1              33              36              37              39   
2               6              23              24              27   

   NUMBER DRAWN 6  BONUS NUMBER  
0              43            13  
1              41             9  
2              39            34

In [6]:
lottery.tail(3)

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
3662      649         3589                0  6/13/2018               6   
3663      649         3590                0  6/16/2018               2   
3664      649         3591                0  6/20/2018              14   

      NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
3662              22              24              31              32   
3663              15              21              31              38   
3664              24              31              35              37   

      NUMBER DRAWN 6  BONUS NUMBER  
3662              34            16  
3663              49             8  
3664              48            17

In [7]:
lottery.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3665 entries, 0 to 3664
Data columns (total 11 columns):
PRODUCT            3665 non-null int64
DRAW NUMBER        3665 non-null int64
SEQUENCE NUMBER    3665 non-null int64
DRAW DATE          3665 non-null object
NUMBER DRAWN 1     3665 non-null int64
NUMBER DRAWN 2     3665 non-null int64
NUMBER DRAWN 3     3665 non-null int64
NUMBER DRAWN 4     3665 non-null int64
NUMBER DRAWN 5     3665 non-null int64
NUMBER DRAWN 6     3665 non-null int64
BONUS NUMBER       3665 non-null int64
dtypes: int64(10), object(1)
memory usage: 315.0+ KB


The data set contains historical data for 3,665 drawings (each row shows data for a single drawing), dating from 1982 to 2018. For each drawing, we can find the six numbers drawn in the following six columns:

- NUMBER DRAWN 1
- NUMBER DRAWN 2
- NUMBER DRAWN 3
- NUMBER DRAWN 4
- NUMBER DRAWN 5
- NUMBER DRAWN 6


## Function for Historical Data Check

Next I am going to write a function that will enable users to compare their ticket against the historical lottery data in Canada and determine whether they would have ever won by now.


In [8]:
def extract_numbers(row):
    row = row[4:10]
    row = set(row.values)
    return row


In [9]:
# extract all the winning numbers
winning_numbers = lottery.apply(extract_numbers, axis=1)
winning_numbers.head()

0    {3, 41, 11, 12, 43, 14}
1    {33, 36, 37, 39, 8, 41}
2     {1, 6, 39, 23, 24, 27}
3     {3, 9, 10, 43, 13, 20}
4    {34, 5, 14, 47, 21, 31}
dtype: object

Lets write a function named check_historical_occurence() that takes in two inputs: a Python list containing the user numbers and a pandas Series containing sets with the winning numbers. The output of this function will be the information  about the number of times the combination inputted by the user occurred in the past and information about the probability of winning the big prize in the next drawing with that combination.

In [10]:
def check_historical_occurence(user_numbers, winning_numbers):
    user_numbers = set(user_numbers)
    check_matches = user_numbers == winning_numbers
    number_check_matches = check_matches.sum()
    if number_check_matches == 0:
        print('This combination of numbers {} was never happend. But your probability of winning the big prize is 0.000007%. Other words your chances is 1 in 13,983,816.'.format(user_numbers))
    else:
        print('This combination of numbers {} was happend {} times in the past. Your probability of winning the big prize is 0.000007%. Other words your chances is 1 in 13,983,816.'.format(user_numbers, number_check_matches))

In [11]:
# test check_historical_occurence(user_numbers, winning_numbers) function

test_user_numbers = [5, 7, 42, 21, 48, 15]
test = check_historical_occurence(test_user_numbers, winning_numbers)

This combination of numbers {5, 7, 42, 15, 48, 21} was never happend. But your probability of winning the big prize is 0.000007%. Other words your chances is 1 in 13,983,816.


In [12]:
# test check_historical_occurence(user_numbers, winning_numbers) function next time

test1_user_numbers = [4, 18, 42, 1, 48, 5]
test1 = check_historical_occurence(test_user_numbers, winning_numbers)


This combination of numbers {5, 7, 42, 15, 48, 21} was never happend. But your probability of winning the big prize is 0.000007%. Other words your chances is 1 in 13,983,816.


## Multi-ticket Probability

Next I am going to write a function that will allow the users to calculate the chances of winning for any number of different tickets.

In [13]:
def multi_ticket_probability(n):
    total_possible_outcomes = combinations(49, 6)
    probability_pcg = n / total_possible_outcomes * 100
    return print('If you buy {} lottery tickets your chances to win will grow on  {:.12f}%'.format(n, probability_pcg))
    

In [14]:
# lets examine our multi_ticket_probability(n) function:

test_func = [1, 10, 100, 10000, 1000000, 6991908, 13983816]

for a in test_func:
    multi_ticket_probability(a)

If you buy 1 lottery tickets your chances to win will grow on  0.000007151124%
If you buy 10 lottery tickets your chances to win will grow on  0.000071511238%
If you buy 100 lottery tickets your chances to win will grow on  0.000715112384%
If you buy 10000 lottery tickets your chances to win will grow on  0.071511238420%
If you buy 1000000 lottery tickets your chances to win will grow on  7.151123842019%
If you buy 6991908 lottery tickets your chances to win will grow on  50.000000000000%
If you buy 13983816 lottery tickets your chances to win will grow on  100.000000000000%


Lottery addicts usually play more than one ticket on a single drawing, thinking that this might increase their chances of winning significantly. Multi_ticket_probability() function calculates the probability for any number of tickets between 1 and 13,983,816

## Less Winning Numbers — Function

For extra context, in most 6/49 lotteries there are smaller prizes if a player's ticket match two, three, four, or five of the six numbers drawn. As a consequence, the users might be interested in knowing the probability of having two, three, four, or five winning numbers.

Next I am going to write one more function to allow the users to calculate probabilities for two, three, four, or five winning numbers.

In [15]:
def probability_less_6(k):
    combination_6_k = combinations(6, k)
    total_number_successful_outcomes = combination_6_k * combinations(43, 6 - k)
    
    total_possible_outcomes = combinations(49, 6)
    
    probability = total_number_successful_outcomes / total_possible_outcomes *100
    combinations_simplified = round(total_possible_outcomes/total_number_successful_outcomes) 
    print('Your chances of having {} winning numbers with this ticket are {:.6f}%. In other words, you have a 1 in {:,} chances to win.'.format(k, probability, int(combinations_simplified)))
     

In [16]:
# test probability_less_6(k) function

for test_input in [2, 3, 4, 5]:
    probability_less_6(test_input)
    print('--------------------------') # output delimiter


Your chances of having 2 winning numbers with this ticket are 13.237803%. In other words, you have a 1 in 8 chances to win.
--------------------------
Your chances of having 3 winning numbers with this ticket are 1.765040%. In other words, you have a 1 in 57 chances to win.
--------------------------
Your chances of having 4 winning numbers with this ticket are 0.096862%. In other words, you have a 1 in 1,032 chances to win.
--------------------------
Your chances of having 5 winning numbers with this ticket are 0.001845%. In other words, you have a 1 in 54,201 chances to win.
--------------------------


I managed to write four main functions for our app:

- one_ticket_probability() — calculates the probability of winning the big prize with a single ticket
- check_historical_occurrence() — checks whether a certain combination has occurred in the Canada lottery data set
- multi_ticket_probability() — calculates the probability for any number of of tickets between 1 and 13,983,816
- probability_less_6() — calculates the probability of having two, three, four or five winning numbers
